###############################################################################
#
# Starts and stops the MeCard (metro) service. 
# Used by systemctl
# Author: Andrew Nisbet andrew.nisbet@epl.case
# Date:   Mon Oct  5 11:53:02 MDT 2020
#   Copyright (C) 2020  Andrew Nisbet, Edmonton Public Library
# The Edmonton Public Library respectfully acknowledges that we sit on
# Treaty 6 territory, traditional lands of First Nations and Metis people.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
###############################################################################

HOME=/home/its/test_metro
LOG=${HOME}/logs
SERVICE=${HOME}/service.sh
SERVICE_NAME=test_mecard
SERVICE_PORT=2005
.PHONY: start stop clean check update
start:
	sudo systemctl start ${SERVICE_NAME}
stop:
	sudo systemctl stop ${SERVICE_NAME}
clean:
	-rm ${LOG}/metro.out
	-rm ${LOG}/metro.err
status:
	sudo systemctl status ${SERVICE_NAME}
check:
	####################
	-cat ${LOG}/metro.out
	####################
	-cat ${LOG}/metro.err
	####################
	ps aux | grep metro
	-netstat -an | grep ${SERVICE_PORT}
