outage:
	cp ./environment.properties ./environment.properties.original
	cp ./environment.properties.outage ./environment.properties
restore:
	cp ./environment.properties.original ./environment.properties 
